name: Update distribution
# Inspired by https://www.edwardthomson.com/blog/building_an_action.html

on:
  push:
    branches: [main]

jobs:
  build-to-dist:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
      - name: Check out distribution branch
        uses: actions/checkout@v2
        with:
          ref: "dist"
          path: "dist"

      - name: Build and package
        run: |
          npm i
          npm run build
          cp action.yml dist/
          cp README.md dist/
          cp LICENSE dist/

      - name: Check for changes
        id: status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=has_changes::yes"
          fi
        working-directory: dist

      - name: Update distribution
        run: |
          git add --verbose .
          git config user.name 'Jeff Israel'
          git config user.email 'github@jeffisrael.com'
          git commit -m 'Update from "publish and package" action'
          git push origin dist
        if: steps.status.outputs.has_changes == 'yes'
        working-directory: dist
